### ISSUE TITLE
eliminate Point

### ISSUE THREAD

**Issue by nhhockeyplayer** [CorentinTh/quadtree-js#22]
Points can be implicitly derived & operated on from whats already housed within the quadtree
specifically the Box

example...

make QuadTree<T> take a generic Box 
make enforce all Box implement a Point interface

add your boxes to quadtree at will with add or addAll for collection of Box[]

eliminate all Shape objects and just enforce implementation of interfaces for users own objects
would drastically reduce footprint
there is already a Point object in the browser angular cdk has one too but I feel an interface is all thats needed to force the creation of user defined shapes

**Comment by CorentinTh** [comment]
I don't think it's a good idea to get rid of the point interface. But removing the point class could be relevent, since it used a the interface. 

Interface will not increase the footprint since they are not compiled for production, they are used only in dev.

Finally, this quadtree is also used in node.js, so they are no Point object that can be used to remplace the Point.
