### ISSUE TITLE
Maximum call stack on large lists

### ISSUE THREAD

**Issue by aJamDonut** [CorentinTh/quadtree-js#5]
Hiya,

Trying to test the library for my game and I'm running into a bit of an issue.

When trying to add more than 1000 points in one call I get a max call exceeded error in chrome

I could slowly add to it using setTimeout or rAF and I'm sure that would resolve the issue. but i'm wondering if there is any async method already build in?

Test code below.

`

function rng(min, max) {
	  return Math.floor(min + Math.random()*(max + 1 - min))
	}
	
	tileSize = 64;
	mapSize = 60;
	mapWidth = tileSize*mapSize;
	
	var qt = new QuadTree(new Box(0,0,mapWidth,mapWidth));
	
	max = 100;
	//max = 1000; //Max call stack exceeded Chrome
	
	for(var z = 0;z<max;z++) {
	
		
		newX = rng(0,mapSize);
		newY = rng(0,mapSize);
		qt.insert(new Point(newX, newY, {name:'random-'+rng(0,1000)}));
		
	}
	

	searchX = 10;
	searchY = 10;
	searchWidth = 10;
	results = qt.query(new Circle(searchX, searchY, searchWidth));
	
	console.error(results);
`

**Comment by aJamDonut** [comment]
For awareness I tested with an interval and it allows me to proceed, sharing in case anyone else finds the issue. Obviously wouldn't use setInterval in the final version.
`	
var addToQT = [];
	max = 1000;
	for(var z = 0;z<max;z++) {
	
		
		newX = rng(0,mapSize);
		newY = rng(0,mapSize);
		addToQT.push(new Point(newX, newY, {name:'random-'+rng(0,1000)}));
		
	}
	
	function addToQT(amount) {
		console.error(qt.query(new Circle(searchX, searchY, searchWidth)));
		if(addToQT.length == 0) {
			return false;
		}
		
		console.log("Add to QT: " + addToQT.length);
		
		var add = addToQT.pop();
		qt.insert(add);
	
	}
	
	
	setInterval(addToQT, 1);`

**Comment by CorentinTh** [comment]
Hi!
Thanks for being interested in Quadtree.

I think the problem here is not the amount of points but the fact that you could have multiple points with the same coordinates.

**What**
As you're picking 1000 points with random coordinates varying between 0 and 60 you have a high change of having points with the same coordinates.

**Why**
When a node get its maximum amount of point, it’ll split into 4 other nodes and dispatch the points between those 4 new nodes. Now, if your points all have the same exact coordinates, they’ll all go the same sub node, which is going to split again, and vice-versa, it’ll go infinitly.

**Possible solutions**
1. I can add a field in the config to ignore duplicates: the qt will not insert a point if it has exactly the same coordinates of an already inserted point.
2. I can add a field in the config to specify a maximum depth for the tree: the last node will have an infinite amount of points, duplicate will not be a problem, but we’ll have a drop in performance using this param.
3. You could make so you insert unique points in the tree, for example by removing the `floor` in your random function.

I'll maybe implement the first 2 options as optional parameters.

Let me now if it has helped you!

**Comment by wetterben** [comment]
Hey Corentin! 

I ran into the same issue and can't resolve it so easy as just removing the floor-function. I would really appreciate an implementation of the second option. Since in my project this state of points with the same position ist always just for one frame, it wouldn't be much of a performance issue. I guess. 

Best regards

PS: Really great work man! Finally a Quad-tree implementation that is easy to use and integrates well with my Typescript project. Thank you!

**Comment by CorentinTh** [comment]
Hi @wetterben,

Thank you for those kind words !

I've implemented the maximum depth option (version 3.1.0).
I let you have a look !

Best regards

**Comment by wetterben** [comment]
Wow, that was really fast! 

Looks great and works like a charm! Perfect, thank you very much. 

Have a nice day!
